"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useBrand } from "@/hooks/use-brand";
import { motion } from "framer-motion";
import { staggerContainer } from "@/lib/motion";
import { SectionHeader } from "@/components/shared/section-header";
import { BrandSelector } from "@/components/layout/brand-selector";
import { ReportCard } from "@/components/reports/report-card";
import { EmptyState } from "@/components/shared/empty-state";
import { Skeleton } from "@/components/ui/skeleton";
import { FileText } from "lucide-react";
import type { TrendReport } from "@/types/report";

export default function ReportsPage() {
  const { activeBrand, loading: brandLoading } = useBrand();
  const [reports, setReports] = useState<(TrendReport & { trend_name?: string })[]>([]);
  const [loading, setLoading] = useState(true);
  const supabase = createClient();

  useEffect(() => {
    async function fetchReports() {
      if (!activeBrand?.id) return;

      const { data } = await supabase
        .from("trend_reports")
        .select("*, trends (name)")
        .eq("brand_id", activeBrand.id)
        .order("generated_at", { ascending: false });

      if (data) {
        setReports(
          data.map((r: any) => ({ ...r, trend_name: r.trends?.name }))
        );
      }
      setLoading(false);
    }

    fetchReports();
  }, [activeBrand?.id, supabase]);

  if (brandLoading || loading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-48" />
        {Array.from({ length: 3 }).map((_, i) => (
          <Skeleton key={i} className="h-32 w-full rounded-xl" />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <SectionHeader
          title="AI Reports"
          description="Strategy reports generated by AI for detected trends"
        />
        <BrandSelector />
      </div>

      {reports.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No reports yet"
          description="AI reports will appear here after trend analysis runs."
        />
      ) : (
        <motion.div
          variants={staggerContainer}
          initial="hidden"
          animate="visible"
          className="space-y-4"
        >
          {reports.map((report) => (
            <ReportCard key={report.id} report={report} />
          ))}
        </motion.div>
      )}
    </div>
  );
}
